### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by FilAleksic** [FilAleksic/mol-mechanics#1]
**Stage 1: Initializing the information**

- [x] Read File
- [x] Read Parameters 
- [x] Initialize bond pointers
- [x] Find 3 pair for Bending
- [x] Find 4 pair for Torsional

**Stage 2: Calculating Energy**

- [x] Stretch Energy
- [x] Bend Energy
- [x] Torsional Energy
- [x] Electrostatic
- [x] Van der Waals

**Step 3: Minimizing Energy**

- [x] Set new value of Energy Function
- [x] Accept new position if
- [x] Termination clause

**Comment by FilAleksic** [comment]
- [x] Evaluate whether more robust bond checking is needed

**Comment by FilAleksic** [comment]
- [ ] DOUBLE CHECK THE BENDING FORMULA Rac^2 ^2 ???

**Comment by FilAleksic** [comment]
- [ ] Double check the math on non bonded
